name: GitHub Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]  # æ¯6å°æ—¶è‡ªåŠ¨æ›´æ–°
  workflow_dispatch:                # å¯æ‰‹åŠ¨è§¦å‘

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          user: hutaoee
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai

          # ğŸ“Š è¯­è¨€ç»Ÿè®¡
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8

          # ğŸ”¥ æ´»è·ƒåº¦ Followup
          plugin_followup: yes

          # ğŸ•˜ ç¼–ç¨‹æ´»è·ƒæ—¶é—´
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          # ğŸš€ è®¿å®¢ç»Ÿè®¡
          plugin_traffic: yes

          # â­ Star å¢é•¿è¶‹åŠ¿
          plugin_stargazers: yes

          # ğŸ“… è¿å‡»æ—¥å†
          plugin_isocalendar: yes

          # ğŸ“ˆ è´¡çŒ®æŠ˜çº¿å›¾
          plugin_lines: yes
